# Servidor
server.port=8080

# Base de datos H2 (desarrollo)
spring.datasource.url=jdbc:h2:mem:taskflowdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# H2 Console (para ver la BD en el navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT
jwt.secret=clave-super-secreta-taskflow-uniquindio-2026-muy-larga
jwt.expiration=86400000

# Actuator
management.endpoints.web.exposure.include=health,info

# Dummy OpenAI key para evitar fallo de autoconfiguración en local
spring.ai.openai.api-key=localdummykey